#!/usr/bin/env bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database role: ${DB_LORA_NS_USER}, ${DB_LORA_AS_USER}"

$POSTGRES <<-EOSQL
CREATE USER ${DB_LORA_NS_USER} WITH CREATEDB PASSWORD '${DB_LORA_NS_PASS}';
CREATE USER ${DB_LORA_AS_USER} WITH CREATEDB PASSWORD '${DB_LORA_AS_PASS}';
EOSQL

